# This Dockerfile is only for purpose of CI, 
# it does not produce production ready images at all!
FROM node:alpine as build

RUN mkdir /app
WORKDIR /app

COPY package*.json /app/
RUN npm install

COPY . /app/
RUN npm run build